version: "3.9"
services:
    app:
        build:
            args:
                user: rickneves
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - rouanet
        depends_on:
            - mysql
            - nginx

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - rouanet

    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/mysql_data:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - rouanet
networks:
    rouanet:
        driver: bridge

volumes:
    mysql_data:
